### ISSUE TITLE
Download without asking distro/confirmation

### ISSUE THREAD

**Issue by BlueCobbleStone** [sxiii/linux-downloader#4]
Hi thanks for this script.

Can you add the support for arguments like `-y ` to download iso without confirming 
or `-d 1,3,4` to choose iso before running the script ?

**Comment by sxiii** [comment]
Hi @BlueCobbleStone :)

That's a good suggestion. I'll look into implementing it!

**Comment by sxiii** [comment]
@BlueCobbleStone 

I have added options you requested and some others. Refactoring might be made in the future, but so far it works.

```
        echo "Valid command line flags:"
	echo "-h/--help: Show this help"
        echo "-y/--noconfirm: Download specified distro without confirmation. "
        echo "-s/--silent: Don't show help or extra info."
        echo "-d/--distro: Download distributions specified in the comma-separated list. Example: 0,2,34"
        exit 0;
```

Please try them out and report back if they work for you, we can close this :) Thanks!

**Comment by BlueCobbleStone** [comment]
It's working perfectly thanks !
